### ISSUE TITLE
Round Up All Cats 

### ISSUE THREAD

**Issue by LucyeoH-zz** [MozillaFoundation/github-playground#10]
Find and tame all cats. :cat: 
This is related to #1

**Comment by hannahkane** [comment]
I don't see how we can do this without doing #9 first.

**Comment by edrushka** [comment]
I shall round up the cats. Can't promise I will tame them, though. @sabrinang might be good for that since she's currently cat-sitting.

**Comment by iamjessklein** [comment]
Let me know if you need help in [cat](http://knowyourmeme.com/memes/serious-cat) wrangling. :dancer: 
![iareseriouscat](https://cloud.githubusercontent.com/assets/535012/5704064/d0d2be46-9a3b-11e4-8885-d419bedbf5c9.jpg)

**Comment by edrushka** [comment]
Whew! It took me 7 months but I did it. All cats are here: 
![room full of cats](https://cloud.githubusercontent.com/assets/4515662/8864360/e6e38772-3155-11e5-8da5-a3763045ca81.jpg)

Closing and going to take some allergy medication.
