### ISSUE TITLE
But what about this thing?

### ISSUE THREAD

**Issue by KathrynMeisner** [MozillaFoundation/github-playground#11]
This relates to both #1 and #2 

:sunglasses:

**Comment by simonwex** [comment]
Hey, @cassiemc, what do you think of this?

/cc @KathrynMeisner @hannahkane @DaveSteer

**Comment by cassiemc** [comment]
Love it. R+

**Comment by DaveSteer** [comment]
Best issue ever.

**Comment by simonwex** [comment]
much awesome, done!

**Comment by hannahkane** [comment]
Could we have MOAR sunglasses, tho?

**Comment by cassiemc** [comment]
:sunglasses::sunglasses::sunglasses:

**Comment by Roberto-Cruz** [comment]
i'm catching up! :)

**Comment by iamjessklein** [comment]
:palm_tree: nice job @KathrynMeisner
