### ISSUE TITLE
Purchase 80 boxes of wafers

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/github-playground#17]
Do this quickly!

**Comment by simonwex** [comment]
Before we do this, we'll need to source them #18 !

**Comment by hannahkane** [comment]
Purchased!

**Comment by iamjessklein** [comment]
phew, they come in 12 packs. 

![516ljyok5gl _aa160_](https://cloud.githubusercontent.com/assets/535012/5704214/5092a352-9a3d-11e4-8c07-760a390d2b6c.jpg)

nice job @edrushka
