### ISSUE TITLE
Source Nilla Wafers from Supplier

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/github-playground#18]
We're going to need a lot. I mean _alot_ [sic]

![image](https://cloud.githubusercontent.com/assets/25260/5688613/3d2920a6-980e-11e4-931e-ca7a7ffb540b.png)

**Comment by simonwex** [comment]
Talked to the supplier, @edrushka they're giving them to us for free, 'cause they love the fox! :cat:

**Comment by iamjessklein** [comment]
![88569d16da94c3e6db7e69b46cba246873e0446312e32d0956fddb97bfb89471](https://cloud.githubusercontent.com/assets/535012/5704187/fd70abd8-9a3c-11e4-8ccd-b37f62467c79.jpg)
