### ISSUE TITLE
Make memaw's banana pudding

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/github-playground#19]
Depends on #18 and #17

**Comment by hannahkane** [comment]
Totes done.

**Comment by elsamozilla** [comment]
trying to learn ## markdown

_making *_everything bold*_, i mean everything_

**Comment by cassiemc** [comment]
@elsamozilla You can use the "preview" tab next to "write" as well, which I find helpful.

**Comment by elsamozilla** [comment]
thanks @cassiemc !!!

**Comment by iamjessklein** [comment]
awesome work @elsamozilla - you can also click the pen icon to see how people wrote their markup. 
There are also [lots of cheatsheets](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) on the interwebs. 
:dancer:
